version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: npm install -D hexo-cli
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Generates static files
          command: ./node_modules/hexo/bin/hexo generate
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git config --global user.name "plyrsbot"
      - run: git config --global user.email "bot@plyrs.app"
      - add_ssh_keys:
          fingerprints:
            - "9b:6b:b8:9a:c5:c0:3e:54:a5:96:80:83:ef:88:42:5f"
      - run: git submodule update --init
      - run: npm install
      - run: ./node_modules/hexo/bin/hexo generate && ./node_modules/hexo/bin/hexo deploy
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
